# Generated by Django 3.1.7 on 2021-04-29 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='Nom',
            new_name='Nom_cat',
        ),
        migrations.RenameField(
            model_name='gamme',
            old_name='Nom',
            new_name='Nom_gam',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Nom',
            new_name='Nom_prod',
        ),
    ]
